apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: iot-app
  template:
    metadata:
      labels:
        run: iot-app
    spec:
      containers:
      - name: iot-monitoring-app
        image: antoniogodoy17/iot-monitoring-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iot-app
spec:
  selector:
    run: iot-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
